spring.application.name=RestCream Project

# Database Configuration (using imported values from Secrets Manager)
spring.datasource.url=jdbc:postgresql://52.72.237.85:5432/scoop_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.file.path=logs